/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [17.64KB] > C:\Users\ohtor\Desktop\le Fede\web-projects\portfolio\public\lentes\scene-transformed.glb [49.78KB] (-182%)
Author: FanoD3c (https://sketchfab.com/fanodev310)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lentes-lucy-2-d27ffa45966949ec96c11b46235dc326
Title: Lentes-lucy-(2)
*/

import React, { useLayoutEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import CustomToonMaterial from "../../threeUtils/customToonMaterial/material";
import { usePortfolio } from "../../context/PortfolioContext";
import { setLentesPoses } from "./setLentesPoses";

export function Lentes(props) {
  const { womanPose } = usePortfolio();
  const { nodes } = useGLTF("lentes/scene-transformed.glb");

  const { position, rotation } = setLentesPoses(womanPose, nodes);

  // #0a0c37
  return (
    <group {...props} position={position} rotation={rotation} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        position={[0, 0.182, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.752}
      >
        <meshToonMaterial color="black" />
      </mesh>

      <mesh
        geometry={nodes.Object_6.geometry}
        position={[0, 0.065, 0]}
        rotation={[Math.PI / 2, 0, 0.017]}
        scale={[1.087, 1.087, 1.099]}
      >
        <meshToonMaterial color={0x0a0c37ff} />
      </mesh>
      <mesh
        geometry={nodes.Object_10.geometry}
        material={new CustomToonMaterial({ red: 0, green: 0, blue: 0 })}
        position={[0, 0, -0.024]}
        scale={[0.032, 0.351, 0.359]}
      />
    </group>
  );
}

useGLTF.preload("lentes/scene-transformed.glb");
