/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [38.93KB] > C:\Users\ohtor\Desktop\le Fede\web-projects\portfolio\public\woman\scene-transformed.glb [374.43KB] (-862%)
Author: camilooh (https://sketchfab.com/camilooh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/womenfemale-body-base-rigged-45caea510e4b4b65bf4ef9bbb4d2045c
Title: Women/Female Body Base Rigged
*/

import React, { useLayoutEffect } from "react";
import { Outlines, useGLTF } from "@react-three/drei";
import CustomToonMaterial from "../threeUtils/customToonMaterial/material";

export function Woman(props) {
  const { nodes, materials } = useGLTF("woman/scene-transformed.glb");

  useLayoutEffect(() => {
    nodes["mixamorigLeftShoulder_08"].rotation.x = 1.5636573071467672;
    nodes["mixamorigLeftShoulder_08"].rotation.y = -0.75;
    nodes["mixamorigLeftShoulder_08"].rotation.z = -1.5990082895108586;

    nodes["mixamorigRightHand_035"].rotation.x = 0.08653752304281702;
    nodes["mixamorigRightHand_035"].rotation.y = 0.9;
    nodes["mixamorigRightHand_035"].rotation.z = 0.19472761828419707;
  }, [nodes]);

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh
        castShadow
        geometry={nodes.Object_85.geometry}
        material={new CustomToonMaterial({ red: 170, blue: 170, green: 0 })}
        skeleton={nodes.Object_85.skeleton}
        position={[0, -0.008, 0]}
        scale={0.161}
      >
        <Outlines thickness={0.008} color="#b200b2" />
      </skinnedMesh>
    </group>
  );
}

useGLTF.preload("woman/scene-transformed.glb");
